CREATE TABLE IF NOT EXISTS `oxconfig` (
  `OXID` char(32) COLLATE latin1_general_ci NOT NULL,
  `OXSHOPID` char(32) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `OXMODULE` varchar(32) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `OXVARNAME` char(32) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `OXVARTYPE` varchar(16) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `OXVARVALUE` blob NOT NULL,
  `OXTIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`OXID`),
  KEY `OXVARNAME` (`OXVARNAME`),
  KEY `listall` (`OXSHOPID`,`OXMODULE`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;